import { useNavigate } from "react-router-dom";
import { FormEvent } from "react";
import Button from "components/Button/Button";
import Input from "components/Input/Input";
import LoginImg from "assets/icons/vendor_login.svg";
import qrcode from "assets/icons/qr_code.svg"
import "./TwoFactor.scss";

const GoogleTwoFactor = () => {
  const navigate = useNavigate();
  const onSubmit = async (e: FormEvent) => {
    e.preventDefault();
    navigate("/google-otp")
  };

  return (
    <div className="landing">
      <div className="right">
        <div className="form">
          <form className="signin" onSubmit={onSubmit}>
            <div className="form-left">
              <img src={LoginImg} alt="login-img" />
            </div>
            <div className="form-right">
              <h2 className="welcome-header">Set up Google Authenticator</h2>
              <p className="two-factor-instruction">
                Please follow the steps below to activate google authenticator
              </p>
              <p className="steps">Step 1: Download and install the app by scanning the QR code</p>
              <img src={qrcode} alt="qr-code"/>
              <p className="steps">Step 2: To register your device, scan this QR code using the Google Authenticator App</p>
              <img src={qrcode} alt="qr-code"/>
              <p className="steps">Step 3: Enter the pass-code generated by Google Autenticator App</p>
          
              <Input type="text" label="Input"/>
              <div className="bottom">
              <Button variant="primary" label="SAVE"/>
              </div>
            
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default GoogleTwoFactor;
